package com.costonomy.mp.identity.provider;

/**
 * Delivers a one-time code to a phone number.
 *
 * <p>A port, per doc 02 §2's external-provider rule: MSG91 in production, a mock
 * everywhere else, and no provider-specific type reaches the domain. The code is
 * generated by {@code OtpService}, not by the provider — that keeps generation,
 * hashing and expiry under our control and makes the mock genuinely equivalent
 * to the real adapter rather than a different flow.
 */
public interface OtpProvider {

    /**
     * Send {@code code} to {@code phone}.
     *
     * @param phone E.164
     * @return the provider's reference for tracing; never the code itself
     * @throws OtpDeliveryException if the provider rejected or could not be reached
     */
    OtpSendResult send(String phone, String code);

    /** {@code MSG91} or {@code MOCK}. Persisted on the challenge for tracing. */
    String name();
}
